#!/bin/sh

PATH="/usr/kerberos/bin:/bin:/usr/bin:/usr/local/bin"
export PATH

# Get AFS tokens for the umich.edu cell

die()
{
	[ -n "$1" ] && echo "$1" 1>&2
	exit 1
}

usage()
{
	die "Usage: gettokens [<user>]"
}


[ $# -eq 0 -o $# -eq 1 ] || usage


if [ $# -eq 0 ]; then
    USER=`id -un`
else
    USER=$1
fi

PRINCIPAL="${USER}@UMICH.EDU"

kinit -5 -l 30d -r 30d "$PRINCIPAL"
[ $? -eq 0 ] || die

aklog -cell umich.edu -k UMICH.EDU
rc=$?

exit $rc
